### ISSUE TITLE
Download files immediately after the first chunk

### ISSUE THREAD

**Issue by sinbadxiii** [nehalvpatel/periscope-downloader#5]
Is it possible to make sure that the file has started to swing immediately after the first chunk?

**Comment by nehalvpatel** [comment]
Do you mean like, save the chunks by just appending them to the first chunk file? Instead of saving them separately then combining them?

**Comment by sinbadxiii** [comment]
@nehalvpatel sorry for my bad English :) I'll try to explain:
Currently downloader does so:
1. It takes an array of chunks with api.periscope
2. Downloads chunks into a temporary folder
3. Merge into one final file
4. Gives to download

Is it possible to download chunks and allow the user to download at the same time? i.e:
1. It takes an array of chunks with api.periscope
2. Downloads chunks into a temporary folder, Merge into one file AND Gives to download
3. Download final file gradually

**Comment by nehalvpatel** [comment]
I think you can do this by pushing the chunks one at a time to the user. Not exactly sure on the implementation though. What are you going to use this for?
